kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: "env-vars"
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://assets.ehealthsystems.nl"
  APP_TIMEZONE: "Europe/Amsterdam"
  APP_LOCALE: "en-US"
  MAX_RESULTS: "500"
  DB_DUMP_PATH: "/usr/bin"
  DB_CONNECTION: "mysql"
  DB_HOST: "snipe-it.cmeulwytdq57.eu-central-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_DATABASE: "snipe-it"
  DB_SSL: "true"
  DB_SSL_IS_PAAS: "true"
  DB_SSL_CA_PATH: "/etc/ssl/certs/aws-global-bundle.pem"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "email-smtp.eu-central-1.amazonaws.com"
  MAIL_PORT: "587"
  MAIL_FROM_ADDR: "assets@ehealthsystems.nl"
  MAIL_FROM_NAME: "Snipe-IT"
  MAIL_REPLYTO_ADDR: "assets@ehealthsystems.nl"
  MAIL_REPLYTO_NAME: "Snipe-IT"
  MAIL_AUTO_EMBED_METHOD: "attachment"
  MAIL_TLS_VERIFY_PEER: "true"
  IMAGE_LIB: "gd"
  SESSION_DRIVER: "database"
  PRIVATE_FILESYSTEM_DISK: "s3_private"
  PUBLIC_FILESYSTEM_DISK: "s3_public"
  PRIVATE_AWS_DEFAULT_REGION: "eu-central-1"
  PRIVATE_AWS_BUCKET: "private.s3.assets.ehealthsystems.nl"
  PRIVATE_AWS_URL: "https://private.s3.assets.ehealthsystems.nl"
  PUBLIC_AWS_DEFAULT_REGION: "eu-central-1"
  PUBLIC_AWS_BUCKET: "public.s3.assets.ehealthsystems.nl"
  PUBLIC_AWS_URL: "https://public.s3.assets.ehealthsystems.nl"