kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "snipe-it"
provisioner: "efs.csi.aws.com"
parameters:
  provisioningMode: "s3files-ap"
  fileSystemId: "fs-01e81f2e5c35aea17"
  directoryPerms: "755"
  uid: "1000"
  gid: "1000"

